# Generated by Django 4.2.24 on 2025-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст чанка')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='Ключевые слова')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Чанк',
                'verbose_name_plural': 'Чанки',
                'ordering': ['-created_at'],
            },
        ),
    ]
