# Generated by Django 4.2.24 on 2025-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_documents/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='Количество чанков')),
            ],
            options={
                'verbose_name': 'Загруженный документ',
                'verbose_name_plural': 'Загруженные документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
